// Canonical prefs for the kiosk Firefox profile (~/.kiosk-firefox).
//
// This is the source of truth. play-video.sh copies it into the live profile
// when the profile is missing the file, and Firefox re-applies user.js on every
// startup, so these prefs can't drift. The rest of ~/.kiosk-firefox (caches,
// history, sqlite dbs) is disposable runtime state generated by Firefox.

// Allow autoplay with sound, no user gesture required
user_pref("media.autoplay.default", 0);
user_pref("media.autoplay.blocking_policy", 0);
user_pref("media.autoplay.allow-extension-background-pages", true);
user_pref("media.autoplay.block-event.enabled", false);
// Skip first-run / what's-new noise in kiosk
user_pref("browser.aboutwelcome.enabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("browser.shell.checkDefaultBrowser", false);
// Never cache: the player assets are local and edited in place, so a cached
// youtube-fullscreen.html would silently serve a stale page after a reload.
user_pref("browser.cache.disk.enable", false);
// Kiosk must always boot straight to the URL — never a crash-recovery or
// session-restore page (which would swallow the launch after an unclean exit).
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("toolkit.startup.max_resumed_crashes", -1);
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.tabs.crashReporting.sendReport", false);
