// Canonical prefs for the kiosk Firefox profile (~/.kiosk-firefox).
//
// This is the source of truth. play-video.sh copies it into the live profile
// when the profile is missing the file, and Firefox re-applies user.js on every
// startup, so these prefs can't drift. The rest of ~/.kiosk-firefox (caches,
// history, sqlite dbs) is disposable runtime state generated by Firefox.

// Allow autoplay with sound, no user gesture required
user_pref("media.autoplay.default", 0);
user_pref("media.autoplay.blocking_policy", 0);
user_pref("media.autoplay.allow-extension-background-pages", true);
user_pref("media.autoplay.block-event.enabled", false);
// Skip first-run / what's-new noise in kiosk
user_pref("browser.aboutwelcome.enabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("browser.shell.checkDefaultBrowser", false);
